//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDeFence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDeFence.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All applications.
        /// </summary>
        internal static string AllApplications {
            get {
                return ResourceManager.GetString("AllApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you initiate the uninstall/update of SimpleDeFence?.
        /// </summary>
        internal static string DidYouInitiateTheUninstall {
            get {
                return ResourceManager.GetString("DidYouInitiateTheUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        internal static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download interrupted..
        /// </summary>
        internal static string DownloadInterrupted {
            get {
                return ResourceManager.GetString("DownloadInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the update server.
        ///The server might be down, or please make sure that SimpleDeFence has been granted internet access, then try again..
        /// </summary>
        internal static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the newest version of SimpleDeFence. No update necessary..
        /// </summary>
        internal static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        internal static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while SimpleDeFence checks for available updates..
        /// </summary>
        internal static string PleaseWaitWhileTinyWallChecksForUpdates {
            get {
                return ResourceManager.GetString("PleaseWaitWhileTinyWallChecksForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleDeFence.
        /// </summary>
        internal static string SimpleDeFence {
            get {
                return ResourceManager.GetString("SimpleDeFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleDeFence Updater.
        /// </summary>
        internal static string TinyWallUpdater {
            get {
                return ResourceManager.GetString("TinyWallUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related files found
        ///The selected executable could be part of {0}. To ensure that this application can be used without limitations, it is recommended to also unblock some other files..
        /// </summary>
        internal static string UnblockApp {
            get {
                return ResourceManager.GetString("UnblockApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel whitelisting.
        /// </summary>
        internal static string UnblockAppCancel {
            get {
                return ResourceManager.GetString("UnblockAppCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide related executables.
        /// </summary>
        internal static string UnblockAppShowRelated {
            get {
                return ResourceManager.GetString("UnblockAppShowRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock all recommended files.
        /// </summary>
        internal static string UnblockAppUnblockAllRecommended {
            get {
                return ResourceManager.GetString("UnblockAppUnblockAllRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock only selected file.
        /// </summary>
        internal static string UnblockAppUnblockOnlySelected {
            get {
                return ResourceManager.GetString("UnblockAppUnblockOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version {0} of SimpleDeFence is available. Do you want to update now?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        

    }
}
