<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RootNamespace>SimpleDeFence.Windows.WFP</RootNamespace>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>
  <PropertyGroup>
    <Product>WFPdotNet</Product>
    <Description>Windows Filtering Platform Interop Library</Description>
    <AssemblyTitle>SimpleDeFence.Windows.WFP</AssemblyTitle>
    <Company>Károly Pados</Company>
    <Copyright>Copyright © 2015 Károly Pados</Copyright>
    <Version>1.1.0</Version>
  </PropertyGroup>
</Project>